### ISSUE TITLE
Button Feature usage for user specific controls

### ISSUE THREAD

**Issue by unevenit** [Kirdock/WillNeverBeFinishedBot#50]
The button feature could be used in the user context for disabling the Intro sounds, for example. 
This should be group dependent of some sort, so only the user himself can remove his intro, but admin's can remove intros from everyone. 

A nice bonus feature would be a button to send a message to the user with a nice little text message and the invite link for the bot (for simple Marketing purposes ;) ).

**Comment by Kirdock** [comment]
Intros are implemented as slash commands (two separate ones for user and admin) #100 

The invite link for the bot is actually available in the profile
![image](https://user-images.githubusercontent.com/11599148/232203215-b5d38d89-b41a-41ea-af6c-1b6b25d28687.png)
